trigger:
  branches:
    include:
    - develop
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
          
- stage: Build
  displayName: Build
  jobs:
    - job: Build
      displayName: Build...
      pool:
        vmImage: $(vmImageName)

      steps:
      
      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
   
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'

- stage: Push
  dependsOn: Build
  displayName: Push
  jobs:
  - job: Push
    displayName: Push...
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: 'passarelacontainers'
        repository: 'intregracao.yunmai.api'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: CopyFiles@2
      displayName: 'Copy YAML'
      inputs:
        contents: '**/*.yaml'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish YAML'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop
