name: API Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and push register app
      uses: docker/build-push-action@v3
      with:
       push: true
       file: ./back/src/jukebox.backend/Dockerfile
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/api.jukebox:latest
