name: API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Build and push  
        uses: docker/build-push-action@v4  
        run: |
          cd ./back/src/jukebox.backend/Dockerfile 
          docker build ... -t postinico/api.jukebox:1.0.0
      
      
