name: API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v4  
        with:
          context: .
          push: true
          file: ./jukebox/back/src/jukebox.backend/Dockerfile
          tags: postinico/api.jukebox:latest
      
      
