name: .NET

variables:
  projectPath: '$back/src/jukebox.backend/*.csproj'
  dockerfilePath: '$back/src/jukebox.backend/Dockerfile'
  nugetfilePath: '$back/src/jukebox.backend/nuget.config'
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
    inputs:
        command: 'restore'
        projects: $(projectPath)
        feedsToUse: config
        nugetConfigPath: $(nugetfilePath)
    
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
